config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "sessions#new"

  get "initialize", to: "projects#init"

  # Link to pages
  get "get_content", to: "pages#get_content"
  get "workspace", to: "projects#index", as: "workspace"
  get "settings", to: "users#settings", as: "settings"

  # Create controllers
  post "highlights/new", to: "highlights#create"
  post "highlighters/new", to: "highlighters#create"
  post "projects/new", to: "projects#create"
  post "pages/new", to: "pages#create"
  post "notes/new", to: "notes#create"

  # Session related
  post "login", to: "sessions#create"
  get "home", to: "sessions#new", as: "home"
  delete "logout", to: "sessions#destroy", as: "logout"
  post "users/new", to: "users#create", as: "signup"

  # Settings page
  patch "projects", to: "projects#add_collab"
  delete "projects/:project_id", to: "projects#destroy"
  get "pages_min/:project_id", to: "pages#get_pages_min"
  delete "pages/:page_id", to: "pages#destroy"
  get "highlighters_min/:project_id", to: "highlighters#get_highlighters_min"
  delete "highlighters/:highlighter_id", to: "highlighters#destroy"

  get "/data_change", to: "projects#data_change"



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/highlight.rb
class Highlight < ApplicationRecord
  belongs_to :highlighter
  belongs_to :page
  has_many :notes
end

app/models/highlighter.rb
class Highlighter < ApplicationRecord
  has_many :highlights
  belongs_to :project
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :highlight
end

app/models/page.rb
class Page < ApplicationRecord
  belongs_to :project
  has_many :highlights
  has_many :notes, through: :highlights
end

app/models/project.rb
class Project < ApplicationRecord
  has_and_belongs_to_many :users
  has_many :pages
  has_many :highlighters
  has_many :highlights, through: [:highlighters, :pages]
  has_many :notes, through: :highlights
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates_uniqueness_of :email
  # validates :email, format: {
  #   with: /\A.*@.*[.].*\z/,
  #   message: "invalid email address"
  # }

  has_and_belongs_to_many :projects

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :fetch_user
  def fetch_user
    @current_user = User.find_by_id(session[:user_id])
  end
end

app/controllers/highlighters_controller.rb
class HighlightersController < ApplicationController
  def create
    new_highlighter = Highlighter.create(name: params[:name], color: params[:color], backgroundColor: params[:backgroundColor], project_id: params[:project_id])
    render json: new_highlighter
  end

  def get_highlighters_min
    render json: Project.find_by_id(params[:project_id]).highlighters.pluck(:id, :name)
  end

  def destroy
    deleted_highlighter = Highlighter.find_by_id(params[:highlighter_id]).destroy
    render json: deleted_highlighter
  end
end

app/controllers/highlights_controller.rb
class HighlightsController < ApplicationController
  def create
    new_highlight = Highlight.create(content: params[:content], page_id: params[:page_id], highlighter_id: params[:highlighter_id])
    # binding.pry
    render json: new_highlight
  end

end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  def create
    new_note = Note.create(content: params[:content], highlight_id: params[:highlight_id])

    render json: new_note.to_json(
      include: {
        highlight: {}
      }
    )
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def get_content
    page = Page.find_by_id(params[:page_id])
    highlighters = page.project.highlighters
    project = Project.find_by_id(Page.find_by_id(params[:page_id]).project.id)

    render json: project.to_json(
      include: {
        pages: {
          include: {
            highlights: {
              include: {
                notes: {}
              }
            }
          }
        },
        highlighters: {
          include: {
            highlights: {
              include: {
                notes: {}
              }
            }
          }
        }
      }
    )
    # render json: {
    #   page: page.to_json(
    #     include: {
    #       highlights: {
    #         include: {
    #           notes: {}
    #         }
    #       }
    #     }
    #   ),
    #   highlighters: highlighters.to_json(
    #     include: {
    #       highlights: {
    #         include: {
    #           notes: {}
    #         }
    #       }
    #     }
    #   )
    # }
  end

  def create
    new_page = Page.create(title: params[:title], content: params[:content], project_id: params[:project_id])

    render json: new_page
  end

  def get_pages_min
    render json: Project.find_by_id(params[:project_id]).pages.pluck(:id, :title)
  end

  def destroy
    deleted_page = Page.find_by_id(params[:page_id]).destroy
    render json: deleted_page
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    if @current_user
      @projects = @current_user.projects
    else
      redirect_to home_path
    end
  end

  def init
    render json: @current_user.projects.to_json(
      include: {
        pages: {
          include: {
            highlights: {
              notes: {}
            }
          }
        },
        highlighters: {
          include: {
            highlights: {
              notes: {}
            }
          }
        }
      }
    )
  end

  def create
    new_project = Project.create(name: params[:name])
    new_project.users << @current_user

    render json: new_project
  end

  def add_collab
    new_collab = User.find_by_email(params[:email])
    project = Project.find_by_id(params[:project_id])

    if !(project.nil? || new_collab.nil?)
      project.users << new_collab
    end

    render json: project
  end

  def destroy
    destroyed_project = Project.find_by_id(params[:project_id]).destroy
    render json: destroyed_project
  end

  def data_change
    curr_project = Project.find_by_id(params[:project_id])

    page_count = curr_project.pages.count
    highlighter_count = curr_project.highlighters.count

    highlight_count = 0
    note_count = 0
    curr_project.highlighters.each do |highlighter|
      highlight_count = highlight_count + highlighter.highlights.count
      highlighter.highlights.each do |highlight|
        note_count = note_count + highlight.notes.length
      end
    end

    return_json = {
      keys: [],
      data: []
    }
    if page_count != params[:page_count].to_i
      return_json[:keys] << 'page'
      return_json[:data] << Page.last
    end

    if highlighter_count != params[:highlighter_count].to_i
      return_json[:keys] << 'highlighter'
      return_json[:data] << Highlighter.last
    end

    if highlight_count != params[:highlight_count].to_i
      return_json[:keys] << 'highlight'
      return_json[:data] << Highlight.last.to_json(
        include: {
          page: {},
          highlighter: {}
        }
      )
    end

    if note_count != params[:note_count].to_i
      return_json[:keys] << 'note'
      return_json[:data] << Note.last.to_json(
        include: {
          highlight: {}
        }
      )
    end

    render json: return_json
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    if @current_user
      redirect_to workspace_path
    end
  end

  def create
    if !(params[:email] =~ /.+@.+\..+/i).nil? # Check if this is in an email format
      user = User.find_by(email: params[:email])
      if user
        if user.authenticate(params[:password])
          session[:user_id] = user.id
          redirect_to workspace_path
        else
          redirect_to home_path
        end
      else
        redirect_to home_path
      end
    end
  end

  def destroy
    session.delete(:user_id)
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def settings
    @projects = @current_user.projects
  end

  def create
    new_user = User.create(name: params[:name], email: params[:email], password: params[:password])

    session[:user_id] = new_user.id
    redirect_to "http://www.rubyonrails.org"
    # redirect_to workspace_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/includes/_flash_notices.html.erb
<% if flash %>
  <% flash.each do |k,v| %>
    <div class="ui message transition <%= k.to_s %>">
      <i class="close icon"></i>
      <div class="header">
        <%= k.to_s.capitalize %>
      </div>
      <p><%= v %></p>
    </div>
  <%end%>
  <% flash.clear %>
<%end%>

app/views/includes/_top_menu.html.erb
<div class="ui inverted vertical masthead center aligned segment">
  <div id="top-menu-inner-cont" class="ui container">
    <div class="ui large secondary inverted pointing menu">
      <div class="top-menu item left">Highlight</div>
      <div class="right item">
        <!-- <a href="#" class="item">Username</a> -->
        <% if @current_user.nil? %>
          <div id="new-user" class="ui inverted button">Sign Up</div>
        <% else %>
          <div class="top-menu item"><%= @current_user.name %></div>
          <div id="page-change-wrap">
            <% if request.env['PATH_INFO'] == '/workspace' %>
              <%= link_to "Settings", settings_path, class: "ui inverted button page-toogle" %>
            <% elsif request.env['PATH_INFO'] == '/settings' %>
              <%= link_to "Workspace", workspace_path, class: "ui inverted button page-toogle" %>
            <% end %>
          </div>
          <%= link_to "Log out", logout_path, class: "ui inverted button", method: "delete" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Highlight</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= render "includes/top_menu" %>
    <div>
      <%= render "includes/flash_notices" %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/projects/index.html.erb
  <div class="projects main-container">

    <div id="project-menu" class="col-md-3">
      <div id="project-title">Projects:</div>
      <hr>
      <div class="ui button" id="new-project">Create new project</div>
      <div class="ui relaxed divided list">
        <% @projects.each do |project| %>
          <div class="item">
            <div class="content project-list" project-id='<%= project.id %>'>
              <div>
                <div class="new-page" project-id="<%= project.id %>">Add Page</div>
                <div class="project-name"><%= project.name %></div>
              </div>
              <% project.pages.each do |page| %>
              <%#binding.pry%>
                <div class="ui button content page-list" page-id='<%= page.id %>'>
                  <% if page.title.length > 45  %>
                    <%= page.title[0..35] %>...
                  <% else %>
                    <%= page.title %>
                  <% end %>
                </div>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
    </div>

    <div id="workspace" class="col-md-5">
      <div id="page-title">Select Page</div>
      <hr>

      <div id="page-container">
        <span id="page-content"></span>
      </div>
    </div>

    <div id="highlighter-menu" class="col-md-4">
      <div id="right-menu-title">
        <span class="right-menu toggler on highlighter">Highlighter</span>
        /
        <span class="right-menu toggler off search">Note</span>
      </div>
      <hr>
      <div id="highlighter-listing"></div>
    </div>

  </div>

  <div class="ui modal" id="new-highlighter-modal">
    <i class="close icon"></i>
    <div class="header">
      Create New Highlighter
    </div>
    <div class="input content">
      <div class="ui container center aligned color">

        <div class="preview center aligned highlighter">Highlighter name</div>

        <div class="ui small input container center aligned highlighter">
          <input class="highlighter input name" type="text" name="name" placeholder="Highlighter name">
        </div>
      </div>
      <div class="ui container center aligned color">
        <div class="highlighter color input-wrap">
          <label for="color">Text Color</label>
          <input class="highlighter input color" type="color" name="color" value="#000000">
        </div>
        <div class="highlighter color input-wrap">
          <label for="backgroundColor">Background Color</label>
          <input class="highlighter input backgroundColor" type="color" name="backgroundColor" value="#FFFF00">
        </div>
      </div>
    </div>
    <div class="actions">
      <div id="close-highlighter" class="ui button">Cancel</div>
      <input id="submit-highlighter" class="ui button primary" type="submit">
    </div>
  </div>

  <div class="ui modal" id="new-page-modal" project-id="">
    <i class="close icon"></i>
    <div class="header">
      Create New Page
    </div>

    <form class="ui form">
      <div class="field">
        <label>Title</label>
        <input id="new-page-title" type="text" name="title" placeholder="Page Title">
      </div>
      <div class="field">
        <label>Content</label>
        <textarea id="new-page-content" name="content" placeholder="Page Content..."></textarea>
        <!-- <input type="text" name="last-name" placeholder="Last Name"> -->
      </div>
      <div class="field">
        <div id="close-page" class="ui button">Cancel</div>
        <input id="submit-page" class="ui button primary" type="submit">
      </div>
    </form>
  </div>

  <div class="ui modal" id="new-project-modal">
    <i class="close icon"></i>
    <div class="header">
      Create New project
    </div>
    <div class="ui input content">
      <input class="new-project-input" type="text" name="name" placeholder="Project name">
    </div>
    <div class="actions">
      <div id="close-project" class="ui button">Cancel</div>
      <input id="submit-project" class="ui button primary" type="submit">
    </div>
  </div>

  <div class="ui modal" id="note-modal" highlight-id="">
    <i class="close icon"></i>
    <div class="header">
      <span>Notes for </span>
      <span class="highlight-name note"></span>
    </div>
    <div id="note-display"></div>
    <form class="ui form">
      <div class="field">
        <label>Note</label>
        <textarea id="new-note-content" name="content" placeholder="Note..."></textarea>
        <!-- <input type="text" name="last-name" placeholder="Last Name"> -->
      </div>
      <div class="field">
        <div id="close-note" class="ui button">Cancel</div>
        <input id="submit-note" class="ui button primary" type="submit">
      </div>
    </form>
  </div>

app/views/users/settings.html.erb
<div class="wrapper">
  <div id="page-header">Settings</div>
  <div class="ui relaxed divided list">
    <div class="item">
      <div class="settings menu items title">Manage Your Projects</div>
      <div>
        <div class="subtitle">Add Collaborator</div>
        <div>
          <div class="ui selection dropdown">
            <input type="hidden" name="project">
            <i class="dropdown icon"></i>
            <div class="default text project">Select project</div>
            <div class="menu">
              <% @projects.each do |project| %>
                <div class="item project collab-project" data-value="<%= project.id %>"><%= project.name %></div>
              <% end %>
            </div>
          </div>
        <div class="ui input">
          <input class="add-collab email" type="text" placeholder="Collaborator email...">
        </div>
        <button class="ui button add-collab submit">
          Add Collaborator
        </button>
        </div>
      </div>

      <div>
        <div class="subtitle">Delete Page</div>
        <div class="ui selection dropdown">
          <input type="hidden" name="project">
          <i class="dropdown icon"></i>
          <div class="default text project">Select project</div>
          <div class="menu">
            <% @projects.each do |project| %>
              <div class="item project delete-page project" data-value="<%= project.id %>"><%= project.name %></div>
            <% end %>
          </div>
        </div>
        <div class="ui selection dropdown">
          <input type="hidden" name="page">
          <i class="dropdown icon"></i>
          <div class="default text page">Select page</div>
          <div class="menu page">
            <!-- <div class="item" data-value="<%# project.id %>"><%# project.name %></div> -->
          </div>
        </div>
        <button class="ui button delete-page submit">
          Delete Page
        </button>
      </div>

      <div>
        <div class="subtitle">Delete Highlighter</div>
        <div class="ui selection dropdown">
          <input type="hidden" name="project">
          <i class="dropdown icon"></i>
          <div class="default text project">Select project</div>
          <div class="menu">
            <% @projects.each do |project| %>
              <div class="item delete-highlighter project" data-value="<%= project.id %>"><%= project.name %></div>
            <% end %>
          </div>
        </div>
        <div class="ui selection dropdown">
          <input type="hidden" name="page">
          <i class="dropdown icon"></i>
          <div class="default text highlighter">Select highlighter</div>
          <div class="menu highlighter">
            <!-- <div class="item" data-value="<%# project.id %>"><%# project.name %></div> -->
          </div>
        </div>
        <button class="ui button delete-highlighter submit">
          Delete Highlighter
        </button>
      </div>

      <div>
        <div class="subtitle">Delete Project</div>
        <div class="ui selection dropdown">
          <input type="hidden" name="project">
          <i class="dropdown icon"></i>
          <div class="default text project">Select project</div>
          <div class="menu">
            <% @projects.each do |project| %>
              <div class="item project delete-project select" data-value="<%= project.id %>"><%= project.name %></div>
            <% end %>
          </div>
        </div>
        <button class="ui button delete-project submit">
          Delete Project
        </button>
      </div>

    </div>

    <div class="item">
      <div class="settings menu items title">Manage Your Account</div>

      <div>
        <div class="subtitle">Change Password</div>
        <div class="ui input">
          <input type="password" placeholder="Current email...">
        </div>
        <div class="ui input">
          <input type="password" placeholder="New email...">
        </div>
        <div class="ui input">
          <input type="password" placeholder="Verify email...">
        </div>
        <button class="ui button">
          Update Password
        </button>
      </div>

      <div>
        <div class="subtitle">Change Your Name</div>
        <div class="ui input">
          <input type="text" placeholder="New name...">
        </div>
        <button class="ui button">
          Update Name
        </button>
      </div>
    </div>
    <!-- <div class="item">
      <div class="settings menu items title">Customize Your Workspace</div>
      <div>
        <div class="subtitle">Toggle with:</div>
      </div>
    </div> -->
  </div>
</div>